dateModified: 1622449988
email:
  fromEmail: jasonloeve@gmail.com
  fromName: Jloeve
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  craftql:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
    settings:
      allowedHeaders:
        - 'Authorization, Content-Type'
      allowedOrigins:
        - '*'
      graphiqlFetchUrl: null
      maxQueryComplexity: false
      maxQueryDepth: false
      throwSchemaBuildErrors: false
      uri: api
      verbs:
        - POST
system:
  edition: solo
  live: true
  name: Jloeve
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
