enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  9a56aa70-b79a-4381-9b88-736975a70b84: # Develop
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
